### ISSUE TITLE
Prompt replacement

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/bashbook#43]
For now just a code lens with working directory, relativized to parent of workspace root if contained in workspace.

### If we wanted to get fancy, but probably won't work
 
Basically a little webview at the top with things like current working directory, etc. 

If easier markdown cell is prob fine for a start

Customisable would be nice but can cross that bridge when we get there

**Comment by AndreasArvidsson** [comment]
I don't think the notebook api allows us to add anything except notebook cells. Of course we could use a cell that just updates with information. I'm not sure how much that would actually help because if you scroll down a bit you won't be able to see it. Maybe we should add this information to a lens instead?

**Comment by AndreasArvidsson** [comment]
Solved by adding a code lens

**Comment by pokey** [comment]
Nice.  Is all this stuff shipped now?

**Comment by AndreasArvidsson** [comment]
yes
