### ISSUE TITLE
Support text mime-type representation

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/bashbook#9]
So that user can eg download output

**Comment by AndreasArvidsson** [comment]
This one is actually quite complicated. 

A normal notebook has the result ready before rendering. Because of this the api only supports replacing the entire output or appending new output cells. 
I now incorrectly use the append output function to send new data from the extension pty to the renderer/xtermjs. This actually creates empty dom elements and is not ideal. 

The notebook api also requires the same number of outputs per mime type. Since we don't want multiple output cells with plain text this becomes a problem.

I need to think long and hard about how to work around this

**Comment by AndreasArvidsson** [comment]
I have a solution now that is working

1. Every time data is sent from the pty run `appendOutput`. This updates the xterm but also creates a lot of empty/hidden div in the dom. At this stage(execution) plain text is not available
2. When execution is finished run `replaceOutput` with both bashbook mime and plaintext. This removes all empty output div and enables plaintext. 


That solution is not perfect. But I think it will suffice for now.
